### ISSUE TITLE
Langstone upgrade

### ISSUE THREAD

**Issue by treboruk** [g4eml/Langstone#37]
Hi I have been using the Langstone for many months now and tried to upgrade the software. When the upgrade completed the Langstone would no longer boot informing me the the boot folder no longer existed.
I have also tried rebuilding an SD card from scratch and I get the same result.
Can anyone advise me please.
Rob G0ECX

**Comment by g4eml** [comment]
Hi Rob, 

I am working on it....  it looks like Raspberry Pi have changed something critical. 
I think I have a fix. It should be ready soon. 

I suggest you try again later this afternoon. 
(You will need to download the latest buster image and start again with a blank card.) 

73 
Colin. 



On 22 Aug 2021, at 13:38, treboruk ***@***.***> wrote:

Hi I have been using the Langstone for many months now and tried to upgrade the software. When the upgrade completed the Langstone would no longer boot informing me the the boot folder no longer existed.
I have also tried rebuilding an SD card from scratch and I get the same result.
Can anyone advise me please.
Rob G0ECX

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by g4eml** [comment]
The install should now be fixed. 
This was caused by the buster status being changed from 'Stable' to 'OldStable'. Presumably in preparation for the release of the new Bullseye revision. 

The Langstone install script has been updated to fix this problem. I would also recommend using the latest Buster Lite image as detailed in the updated instructions. 

When Bullseye is released I will try to transfer Langstone to that revision. 

Colin G4EML

**Comment by treboruk** [comment]
Hi Colin

Many thanks, all working fine again now. This is a great project that I very much enjoyed building and using mostly on QO100 but I have also bult a PA for 70Cms.

Sorry to disturb you on a Sunday but I did not expect you to reply so quickly.

The Langstone is a great way of getting on the higher bands. I have attached a picture of my version of the Langstone for you.

Best Regards

Rob Mott
G0ECX
