### ISSUE TITLE
cp: error writing '/dev/fb0' : no space left on device

### ISSUE THREAD

**Issue by EA7TB110** [g4eml/Langstone#47]
Hello.
I have made the installation on a Raspberry pi 4 with the 7" Touchscreen Display.
The installation has been done correctly.
But when the "run" script is executed, I get the error: "cp: error writing '/dev/fb0': No space left on device".
Could you tell me how to solve the problem?
Greetings.
Manuel EA7TB

**Comment by g4eml** [comment]
Hello Manuel, 

I have just performed the installation with a fresh SD card, and all is still working correctly. 
So that would indicate that something must have failed during your installation. 

I would suggest you repeat the process and make sure you follow all of the steps in the Github instructions. 

/dev/fb0 is the frame buffer for the display, so if it is failing then it would point to something being wrong with the display installation. 

Are you using the official raspberry pi 7” display and only that display?  Make sure you do not have an HDMI display connected as well. 

Colin G4EML







From: EA7TB110
Sent: 28 June 2022 22:59
To: g4eml/Langstone
Cc: Subscribed
Subject: [g4eml/Langstone] cp: error writing '/dev/fb0' : no space left ondevice (Issue #47)

Hello.
I have made the installation on a Raspberry pi 4 with the 7" Touchscreen Display.
The installation has been done correctly.
But when the "run" script is executed, I get the error: "cp: error writing '/dev/fb0': No space left on device".
Could you tell me how to solve the problem?
Greetings.
Manuel EA7TB

**Comment by g4eml** [comment]
Hello Manuel, 

The warning is not important, but I don’t get it when I do the install so something is strange. 
If you are following the instructions exactly then you should get the same result. 

Are you using the recommended Buster Lite version? 

https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip

Also it looks like the wiringPi package was not installed correctly. 
You could try running the commands from the install.sh script manually and checking for errors. 

cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb
cd ~


Colin.

**Comment by EA7TB110** [comment]
Hi Colin
I have started from scratch, new card and I have recorded the image with the Raspbian program "Raspberry Pi Imager", in a new SD card.
Now if Langstone has been installed without any problem.
Thanks for your help.
Greetings Manuel EA7TB
73'

**Comment by g4eml** [comment]
Hi Manuel, 

That’s good news. 

73
Colin. 


On 30 Jun 2022, at 14:32, EA7TB110 ***@***.***> wrote:

Hi Colin
I have started from scratch, new card and I have recorded the image with the Raspbian program "Raspberry Pi Imager", in a new SD card.
Now if Langstone has been installed without any problem.
Thanks for your help.
Greetings Manuel EA7TB
73'
