### ISSUE TITLE
Pluto segmentation fault

### ISSUE THREAD

**Issue by pe4wj** [g4eml/Langstone#49]
After not having used my Langstone for quite a while I started using it again, but it complains that Lang_tx.py can't find the Pluto, and when I run `Pluto_test` I'm getting a segfault:
![image](https://github.com/g4eml/Langstone/assets/47270032/a878fce0-7d21-4d0b-aaf5-5477be6d863b)

I've then done a clean install of Langstone as per the instructions using a different (new) SD card. I've also updated Pluto firmware version v.037. I am using a Pluto RevD. After these steps, the issue still persists.

Many thanks in advance for your help!

73,

Wouter Jan PE4WJ

**Comment by pe4wj** [comment]
I've just tried a clean install of Langstone-V2 and got exactly the same issue (also reported in the Langstone V2 repo)

**Comment by g4eml** [comment]
Hello, 

I have just done a fresh build of Langstone V2 and can confirm that the build is still working correctly. Pluto_Test also works correctly.   So, assuming you followed all the install instructions, your problem is not a software one.
 
From the Pluto_Test results your Pluto is being detected OK but is failing as soon as it is put under load. 
That could be cause by many things. However the most common Pluto problem is with the power supply. 

The Pluto is very sensitive to power supply voltage and ground loops. From my own experience and that of several others in the DATV community  it seems to work best at slightly below 5V input. Something like 4.75V.  This goes against the normal practice of ensuring the voltage is above 5V which the Raspberry Pi prefers. We don’t really know why this is the case.  Some people have had good results adding a diode in series with the 5V supply to the Pluto to reduce the voltage while leaving the Raspberry pi supply at slightly above 5V. 

So all I can suggest is to try thigs associated with the Pluto connection. Change the cable. Try a different USB socket. Try a different power supply. 

Colin. G4EML


 

From: pe4wj
Sent: 18 September 2023 07:49
To: g4eml/Langstone
Cc: Subscribed
Subject: [g4eml/Langstone] Pluto segmentation fault (Issue #49)

After not having used my Langstone for quite a while I started using it again, but it complains that Lang_tx.py can't find the Pluto, and when I run Pluto_test I'm getting a segfault:

I've then done a clean install of Langstone as per the instructions using a different (new) SD card. I've also updated Pluto firmware version v.037. I am using a Pluto RevD. After these steps, the issue still persists.
Many thanks in advance for your help!
73,
Wouter Jan PE4WJ

**Comment by pe4wj** [comment]
For the record: turned out the issue was due to an incorrect firmware update on the Pluto, my Pluto is a RevC and there you have to copy the entire contents of the firmware zip folder onto the USB drive to update it (see the note under "Mass Storage Update" here https://wiki.analog.com/university/tools/pluto/users/firmware ). It works now, thanks Colin!
